version: "3.8"
services:
  db:
    image: docker.io/postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

  adminer:
    image: docker.io/adminer:latest
    container_name: adminer_container
    restart: always
    ports:
      - 8080:8080
